---
apiVersion: v1 
kind: Secret 
metadata: 
  name: keycloak-db-secret 
  namespace: rhsso-dev
stringData: 
  POSTGRES_DATABASE: "pgsql-rhsso-dev"
  POSTGRES_USERNAME: "pgsql-admin"
  POSTGRES_PASSWORD: "pgsql-password"
  POSTGRES_EXTERNAL_ADDRESS: "keycloak-postgresql.rhsso-dev.svc.cluster.local"
  POSTGRES_EXTERNAL_PORT: "5432"
# of course we have to change the values to real ones