---
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: rhsso-dev
  labels:
    app: rhsso-dev
  namespace: rhsso-dev
spec:
  externalAccess:
    enabled: true
  instances: 2
  keycloakDeploymentSpec:
    imagePullPolicy: Always
  postgresDeploymentSpec:
    imagePullPolicy: Always
  storageClassName: gp2
#  storageClassName: ocs-external-storagecluster-ceph-rbd

