apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 00_namespace_rhsso-dev.yaml
- 01_rhsso-operator_resourcegroups.yaml
# - 01_secret_rhsso-dev-database.yaml
- 02_rh-sso-operator.yaml
- 03_deploy_rhsso-dev.yaml
- 04_rh-sso-hpa.yaml
# 05_rh-sso-route.yaml