kind: Keycloak
apiVersion: k8s.keycloak.org/v2alpha1
metadata:
  name: keycloak-development
  labels:
    app: sso
  namespace: keycloak
spec:
  hostname: example.org
  instances: 1
  tlsSecret: my-tls-secret
