kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "3"
  name: keycloak-development
  namespace: keycloak
  labels:
    app: keycloak
    app.kubernetes.io/instance: keycloak-development
    app.kubernetes.io/managed-by: keycloak-operator
spec:
  to:
    kind: Service
    name: keycloak-development-service
  tls: null
  port:
    targetPort: https
