---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "8"
  name: openldap
  namespace: keycloak
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "9"
  name: anyrole
  namespace: keycloak
subjects:
  - kind: ServiceAccount
    name: openldap
    namespace: keycloak
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "10"
  namespace: keycloak
  name: ldap
spec:
  serviceAccount: openldap
  selector:
    matchLabels:
      app: ldap
  replicas: 1
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
        - name: container
          image: rroemhild/test-openldap
          ports:
            - containerPort: 8080
              protocol: TCP
          env: []
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
---
apiVersion: v1
kind: Service
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "11"
  name: openldap
  namespace: keycloak
spec:
  selector:
    app: ldap
  ports:
    - protocol: TCP
      port: 80
      targetPort: 10389